name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: show work dir
        run: pwd

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check out and Pull code
        run: git fetch origin &&  git stash save &&  git checkout main && git pull
        
      - name: Build the Docker image
        run: docker build -t test .

      - name: Run docker container
        run: docker run -dp 8081:8081 --name=test test
      
