name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  setup:
    runs-on: self-hosted
    steps:

      - name: Check out repository code
        id: checkout
        uses: actions/checkout@v3
        continue-on-error: true

      - name: Send email
        if: steps.checkout.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build failure
          to: foxbeel@gmail.com
          from: Twendee Soft
          body: Build job of ${{github.repository}} failure, because cannot checkout
  build:
    needs: setup
    runs-on: self-hosted

    steps:
      - name: Build the Docker image
        id: build
        run: docker build -t test .
        continue-on-error: true

      - name: Send email
        if: steps.build.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build failure
          to: foxbeel@gmail.com
          from: Twendee Soft
          body: Build job of ${{github.repository}} failure, because build docker error

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        id: test
        run: mvn test
        continue-on-error: true

      - name: Send email
        if: steps.test.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build failure
          to: foxbeel@gmail.com
          from: Twendee Soft
          body: Build job of ${{github.repository}} failure, because test failure

  deploy:
    needs: [build, test]
    runs-on: self-hosted
    steps:
      - name: Stop docker container
        run: docker stop test || true && docker rm test || true

      - name: Run docker container
        id: run
        run: docker run -dp 8081:8081 --name=test test
        continue-on-error: true

      - name: Send email success
        if: steps.run.outcome == 'success'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build failure
          to: foxbeel@gmail.com
          from: Twendee Soft
          body:  Build job of ${{github.repository}} completed successfully!

      - name: Send email success
        if: steps.run.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Build failure
          to: foxbeel@gmail.com
          from: Twendee Soft
          body: Build job of ${{github.repository}} failure, because cannot run docker container!