name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  setup:
    runs-on: self hosted
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3

  build:
    needs: setup
    runs-on: self-hosted

    steps:
      - name: Build the Docker image
        run: docker build -t test .

#  test:
#    needs: setup
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - name: Build with Maven
#        run: mvn test


  deploy:
    needs: [build, test]
    runs-on: self hosted
    steps:
      - name: Stop docker container
        run: docker stop test || true && docker rm test || true

      - name: Run docker container
        run: docker run -dp 8081:8081 --name=test test
      
